# Application Name
spring.application.name=risk-reporting-suite

# Server Port
server.port=8080

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/risk_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Day 2 Completed
# Entity + Repository + DB Connected